# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Runner
   pod 'Firebase/Analytics'
   pod 'Firebase/Core'
   pod 'Firebase/Messaging'
end
